config/routes.rb
Rails.application.routes.draw do
  resources :segments
  resources :enrollments
  resources :users
  get '/users_courses', to: 'users#user_courses'
  get '/search_course', to: 'courses#search'
  get 'search_courses_list', to: 'courses#search_by_name_and_subject'
  post '/enroll/:course_id',to: 'users#enroll', as: :enroll_path
  post '/unenroll/:course_id',to: 'users#unenroll', as: :unenroll_path
  resources :subjects
  resources :courses
  resources :instructors
  root 'index#index' , as: :index_path

  get '/login', to: 'session#new'
  post '/login' ,to: 'session#login', as: :login_path
  get '/signup', to: 'users#new' ,as: :signup_path
  post '/signup', to: 'users#signup'
  post '/logout', to:'session#delete', as: :logout_path
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  self.primary_key="id"
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first, :middle, :last, :id, :type)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :middle %>
    <%= form.text_field :middle %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-primary"%>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor, class:"btn btn-outline-primary" %> |
<%= link_to 'Back', 'javascript:history.back()', class:"btn btn-outline-primary" %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table class="table">
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.first %></td>
        <td><%= instructor.last %></td>
        <td><%= instructor.id %></td>
        <td><%= link_to 'Show', instructor , class:"btn btn-outline-primary"%></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) , class:"btn btn-outline-primary"%></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline-primary"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path, class:"btn btn-outline-primary" %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', 'javascript:history.back()', class:"btn btn-outline-primary" %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @instructor.first %>
</p>

<p>
  <strong>Middle:</strong>
  <%= @instructor.middle %>
</p>

<p>
  <strong>Last:</strong>
  <%= @instructor.last %>
</p>

<p>
  <strong>Id:</strong>
  <%= @instructor.id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @instructor.type %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor), class:"btn btn-outline-primary" %> |
<%= link_to 'Back', 'javascript:history.back()', class:"btn btn-outline-primary" %>