config/routes.rb
Rails.application.routes.draw do
  resources :segments
  resources :enrollments
  resources :users
  get '/users_courses', to: 'users#user_courses'
  get '/search_course', to: 'courses#search'
  get 'search_courses_list', to: 'courses#search_by_name_and_subject'
  post '/enroll/:course_id',to: 'users#enroll', as: :enroll_path
  post '/unenroll/:course_id',to: 'users#unenroll', as: :unenroll_path
  resources :subjects
  resources :courses
  resources :instructors
  root 'index#index' , as: :index_path

  get '/login', to: 'session#new'
  post '/login' ,to: 'session#login', as: :login_path
  get '/signup', to: 'users#new' ,as: :signup_path
  post '/signup', to: 'users#signup'
  post '/logout', to:'session#delete', as: :logout_path
end

app/models/segment.rb
class Segment < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:id, :course_id, :subject_id)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_with(model: segment, local: true) do |form| %>
  <% if segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :segment_id %>
    <%= form.number_field :segment_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.number_field :subject_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Segments</h1>

<table>
  <thead>
    <tr>
      <th>Segment</th>
      <th>Course</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.segment_id %></td>
        <td><%= segment.course_id %></td>
        <td><%= segment.subject_id %></td>
        <td><%= link_to 'Show', segment %></td>
        <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_segment_path %>

app/views/segments/new.html.erb
<h1>New Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Back', segments_path %>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Segment:</strong>
  <%= @segment.segment_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @segment.course_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @segment.subject_id %>
</p>

<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>